server:
 port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
#    url : jdbc:mysql://127.0.0.1:3306/oauth2
    username : yong
    password : 123456
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    min-idle : 5
    max-wait : 6000
    test-while-idle : true
    test-on-borrow : true
    initial-size : 10
    validation-query : SELECT  1 FROM DUAL

  redis:
      database: 1
      host: 127.0.0.1
      password: 123456
      port: 6379
      timeout: 0
      test-while-idle : true
      test-on-borrow : true
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3